### ISSUE TITLE
LS120 Support 

### ISSUE THREAD

**Issue by Veldkornet** [rkoebrugge/hacs-youless-component#2]
Could you please add support for the LS120? I'm currently using [this](https://github.com/reharmsen/hass-youless-component) which is where you forked from... but it doesn't seem to be maintained.

Additionally, with this, the ability to use the s0 input as a water meter instead. Maybe a boolean in the settings?

Currently, I use a [Pulssensor Cyble voor watermeters Itron](https://www.homewizard.nl/pulsesensor-cyble-voor-watermeters-itron) connected to the s0 port. I just modified the sensor.py and just changed the labels (for example, below). I checked with Youless themselves who confirmed that this provides the correct data.

```
    'cs0': ['Water Meter', 'water_meter', 'm3', 'mdi:gauge', 'energy.png'],
    'ps0': ['Current Water usage', 'current_water_usage', 'L/min', 'mdi:water', 'water.png']
```

**Comment by rkoebrugge** [comment]
Hi @Veldkornet ,

I don't have a LS120 so I can't test if it is working properly. You are free to fork the code and configure it for your own sensor off course.

Or try to reach out to reharmsen and see if he test the code for your situation?

**Comment by Veldkornet** [comment]
Thing is, this one is in HACS so it's easy to update etc, that's how I found it :)

**Comment by rkoebrugge** [comment]
Yeah, I understand. What I changed for supporting the LS110 is the requested URL. Most likely the LS120 doesn't give you the cs0 and ps0 value on this changed request so therefore I cannot add it.

The reharmsen integration is also in HACS btw.
